#############################################################################################################################################
#
#    Define feature-based classes of segments and count them on PHOIBLE and Ruhlen's (Creanza et al 2015) databases.
#    Copyright (C) 2014-2015  Dan Dediu <ddediu@gmail.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#############################################################################################################################################

library(stringr);  # string processing
library(parallel); # multicore processing

parallel.mc.cores = 4;

######################################################################################
#
# The languages are those assembled from wals, ethnologue and glottolog
#
######################################################################################
languages <- read.table( "../input/code_mappings_iso_wals_autotyp_glottolog.csv", header=TRUE, sep="\t", quote="", stringsAsFactors=FALSE ); # this file was generated by another script not included here  (but discussed elsewhere) using only public data
languages$AUTOTYP <- as.character(languages$AUTOTYP); languages$AUTOTYP[ is.na(languages$AUTOTYP) ] <- ""; # make sure the AUTOTYP code is treated as character with missing data as ""
# Keep only the languages with geographical info:
languages <- languages[ !is.na(languages$Latitude) & !is.na(languages$Longitude), ];
# Keep only those with at least Glottolog or ISO codes:
languages <- languages[ languages$ISO != "" | languages$Glottolog != "", ];
# Collapse entries with the same Glotolog and ISO codes but multiple WALS and/or AUTOTYP codes together
unique.lgs <- unique(languages[,c("ISO","Glottolog")]);
languages2 <- lapply(1:nrow(unique.lgs), function(i)
  { 
    # Find the corresponding languages:
    tmp <- languages[ languages$ISO == unique.lgs$ISO[i] & languages$Glottolog == unique.lgs$Glottolog[i], ];
    if( nrow(tmp) == 1 ) return (tmp);
    # Create the UULID:
    uulid <- paste0("[i-",unique.lgs$ISO[i],"]",
                    "[w-",paste0(unique(tmp$WALS[tmp$WALS!=""]),collapse="-"),"]",
                    "[a-",paste0(unique(tmp$AUTOTYP[tmp$AUTOTYP!=""]),collapse="-"),"]",
                    "[g-",unique.lgs$Glottolog[i],"]");
    # Sort the entries by informativity (weight coordinates, then WALS and then AUTOTYP):
    scores <- 10*as.numeric(!is.na(tmp$Latitude)) + 10*as.numeric(!is.na(tmp$Longitude)) + 2*as.numeric(tmp$WALS!="") + as.numeric(tmp$AUTOTYP!=""); names(scores) <- 1:length(scores);
    scores <- sort(scores,decreasing=TRUE);
    # Combine the entries:
    e <- tmp[as.numeric(names(scores)[1]),]; e$UULID <- uulid;
    for( j in 1:ncol(e) ) if( is.na(e[,j]) || e[,j]=="" ) 
    {
      indices <- sapply(2:length(scores), function(k){ v <- tmp[as.numeric(names(scores)[k]),j]; ifelse( is.na(v) || v=="", NA, as.numeric(names(scores)[k]) ) });
      indices <- indices[!is.na(indices)];
      if( length(indices) > 0 ) e[,j] <- tmp[indices[1],j];
    }
    return (e);
  } );
languages <- do.call(rbind, languages2);
write.table(languages, "../output/languages-info.csv", quote=FALSE, sep="\t", row.names=FALSE);
rm(unique.lgs);
    

######################################################################################
#
# Assemble the segments from PHOIBLE, Ruhlen, and WALS
#
######################################################################################
cat( "Processing the inventories...\n" );
  
# The PHOIBLE inventories:
phoible.phonemes <- read.table( "../input/phoible-phonemes.tsv", header=TRUE, sep="\t", quote="\"", na.strings="NULL", stringsAsFactors=FALSE );
phoible.phonemes <- phoible.phonemes[ phoible.phonemes$Trump == 1, c( "LanguageCode", "GlyphID", "Phoneme", "Class" ) ];
names(phoible.phonemes)[1] <- "ISO";
phonemes <- as.character( unique( phoible.phonemes$Phoneme ) ); phonemes <- sort( phonemes );
phoible.inventories <- matrix( NA, nrow=nrow(languages), ncol=length(phonemes) ); colnames(phoible.inventories) <- phonemes;
phoible.inventories <- cbind( languages, phoible.inventories );
# Slow but clear:
tokeep <- rep(FALSE,nrow(phoible.inventories));
for( i in 1:nrow(phoible.inventories) )
{
  if( i %% 1000 == 1 ) cat("Processing inventory ", i, " out of ", nrow(phoible.inventories), "(", sprintf("%.1f",100*i/nrow(phoible.inventories)), "%)...\n");
  if( phoible.inventories$ISO[i] != "" )
  {
    s <- (phoible.phonemes$ISO == phoible.inventories$ISO[i]);
    if( sum(s,na.rm=TRUE) > 0 )
    {
      phoible.inventories[ i, 12:ncol(phoible.inventories) ] <- 0;
      for( j in which(s) )
      {
        phoible.inventories[ i, colnames(phoible.inventories) == phoible.phonemes$Phoneme[j] ] <- 1;
      }
      tokeep[i] <- TRUE;
    }
  }
}
# Keep only those with actual data:
phoible.inventories <- phoible.inventories[ tokeep, ];
phoible.inventories <- phoible.inventories[ order(phoible.inventories$UULID), ];
save(phoible.inventories, file="../output/inventories-phoible.RData", compress="xz");
  
# The Ruhlen (Creanza et al., 2015) inventories, extracted from the SI files pnas.1424033112.sd01.txt and pnas.1424033112.sd02.txt (see description of the format in these files):
# Get the segments from pnas.1424033112.sd02.txt:
tmp <- read.table("../input/pnas.1424033112.sd02.txt", header=TRUE, sep="\t", quote="", stringsAsFactors=FALSE, skip=15); # skip the description
rhulen.segments <- tmp$Phoneme; names(rhulen.segments) <- tmp$Column;
# Get the occurences from pnas.1424033112.sd01.txt:
rhulen.phonemes <- read.table("../input/pnas.1424033112.sd01.txt", header=FALSE, sep="\t", quote="", stringsAsFactors=FALSE, skip=19); # skip the description
# Remove duplicates by keeping only the first entry:
rhulen.phonemes <- rhulen.phonemes[ !duplicated(rhulen.phonemes$V3), ];
# Merge with the language info I already have using the ISO:
rhulen.inventories <- merge(languages, rhulen.phonemes, by.x="ISO", by.y="V3"); 
rhulen.inventories <- rhulen.inventories[, -(12:19)];
rhulen.inventories <- rhulen.inventories[ order(rhulen.inventories$UULID), ];
# Give them appropriate names:
names(rhulen.inventories)[12:ncol(rhulen.inventories)] <- rhulen.segments;
save(rhulen.inventories, file="../output/inventories-rhulen.RData", compress="xz");
# Remove from Ruhlen the "c" and "v" (and variants):
rhulen.inventories <- rhulen.inventories[, -c(grep("c",names(rhulen.inventories),fixed=TRUE), grep("v",names(rhulen.inventories),fixed=TRUE))];

# Build a list with all unique segments we have:
segments <- union(names(phoible.inventories)[(which(names(phoible.inventories)=="UULID")+1):ncol(phoible.inventories)],
                  names(rhulen.inventories)[(which(names(rhulen.inventories)=="UULID")+1):ncol(rhulen.inventories)]);
  
  
  
  


##############################################
#
# The featural systems (Phoible & Fonetikode)
# for the Phoible & Ruhlen databases
#
##############################################

# PHOIBLE features:
phonemes.phoible <- read.table( "../input/phoible-segments-features.tsv", header=TRUE, sep="\t", quote="", stringsAsFactors=FALSE );
names(phonemes.phoible) <- c("Phoneme", "tone", "stress", "syll", "short", "long", "cons", "sonorant", "cont", "delayRel", "approx", "tap", "trill", "nasal", "lateral", "labial", "round", "labiodent", "coronal", "anterior", "distrib", "strident", "dorsal", "high", "low", "front", "back", "tense", "rtr", "atr", "perGlotSrc", "epilarSrc", "spreadGlot", "constrGlot", "fortis", "raisedLarynxEject", "loweredLarynxImpl", "click"); # makes names shorter

# Fonetikode features:
phonemes.fonetikode <- read.table( "../input/phoible_Features_Fonetikode.csv", header=TRUE, sep="\t", quote="", na.strings="", stringsAsFactors=FALSE );
phonemes.fonetikode <- phonemes.fonetikode[, -c(ncol(phonemes.fonetikode)) ]; # exclude the notes
names(phonemes.fonetikode) <- c( "ID", "Phoneme", "GC", "VV", "VH", "VM", "CP", "CM", "CS", "Phon", "Init", "Pri", "Sec", "Pros", "Tone" );

# Fonetikode features for Ruhlen's database:
phonemes.rhulen <- read.table( "../input/Ruhlen_Features_Fonetikode.csv", header=TRUE, sep="\t", quote="", na.strings="", stringsAsFactors=FALSE );
phonemes.rhulen <- phonemes.rhulen[, -c(2,(ncol(phonemes.rhulen)-2):ncol(phonemes.rhulen)) ]; # exclude the notes
names(phonemes.rhulen) <- c( "Phoneme", "GC", "VV", "VH", "VM", "CP", "CM", "CS", "Phon", "Init", "Pri", "Sec", "Pros", "Tone" );
phonemes.rhulen <- phonemes.rhulen[ rowSums(!is.na(phonemes.rhulen[,-1])) > 0, ]; # get rid of the undefined phonemes

# Look for duplicates:
d <- duplicated( as.character(phonemes.fonetikode$Phoneme ) );
if( sum(d) > 0 )
{
  for( i in which(d) )
  {
    cat( paste0("Duplicated segment \"", as.character(phonemes.fonetikode$Phoneme[i] ), "\" at rows ", paste( which( phonemes.fonetikode$Phoneme == phonemes.fonetikode$Phoneme[i] ), collapse=", " ), "\n"));
  }
}
d <- duplicated( as.character(phonemes.rhulen$Phoneme.Ruhlen ) );
if( sum(d) > 0 )
{
  for( i in which(d) )
  {
    cat( paste0( "Duplicated Ruhlen segment \"", as.character(phonemes.rhulen$Phoneme.Ruhlen[i] ), "\" at rows ", paste( which( phonemes.rhulen$Phoneme.Ruhlen == phonemes.rhulen$Phoneme.Ruhlen[i] ), collapse=", " ), "\n"));
  }
}

# Keep only the actually used segments in each featural system/database:
phonemes.phoible  <- phonemes.phoible[ as.character(phonemes.phoible$Phoneme) %in% intersect( names(phoible.inventories), as.character(phonemes.phoible$Phoneme) ), ];
phonemes.fonetikode  <- phonemes.fonetikode[ as.character(phonemes.fonetikode$Phoneme) %in% intersect( names(phoible.inventories), as.character(phonemes.fonetikode$Phoneme) ), ];
phonemes.rhulen <- phonemes.rhulen[ as.character(phonemes.rhulen$Phoneme) %in% intersect( names(rhulen.inventories), as.character(phonemes.rhulen$Phoneme) ), ];




############################################################
#
# The feature counts
# this is highly customizable and depends on the problem
#
############################################################

library(compiler);
# Helper functions:
# Given a feature and a corresponding feature value and the subset of phonemes corresponding to an inventory, return the boolean vector of phoneme matches:
find.matching.phonemes <- function( phonemes.subset, feature, value )
{
  s <- (names(phonemes.subset) == feature);
  if( !any(s) )
  {
    ## Feature not found, consider no match!
    return( rep( FALSE, nrow(phonemes.subset) ) );
  }
  return( vapply( as.character(phonemes.subset[,s]), function( v ){
                                                     if( is.na(v) )
                                                     {
                                                       return( FALSE ); # no macth
                                                     } else
                                                     {
                                                       # There could be more than one value separated by space or comma:
                                                       return( any(value %in% strsplit( v, "[ ,]" )[[1]]) );
                                                     }
                                                   }, logical(1) ) );
}
find.matching.phonemes <- cmpfun(find.matching.phonemes);

# Given a feature and the subset of phonemes corresponding to an inventory, return the unique values of the feature in the inventory as a list of vectors of values:
unique.feat.vals <- function( phonemes.subset, feature )
{
  s <- (names(phonemes.subset) == feature);
  if( !any(s) )
  {
    ## Feature not found, consider no match!
    vals <- lapply(1:nrow(phonemes.subset),function(i) return(NULL));
    names(vals) <- as.character(phonemes.subset$Phoneme);
    return( vals );
  }
  vals <- lapply( as.character(phonemes.subset[,s]), function( v ){
                                                     if( is.na(v) )
                                                     {
                                                       return( c() ); # no macth
                                                     } else
                                                     {
                                                       # There could be more than one value separated by space or comma:
                                                       return( strsplit( v, "[ ,]" )[[1]] );
                                                     }
                                                   } );
  names(vals) <- as.character(phonemes.subset$Phoneme);
  return( vals );
}
unique.feat.vals <- cmpfun(unique.feat.vals);

# For a given inventory, return the phonemes that contain the given segment:
is.variant.of <- function( phonemes.subset, segment )
{
  vapply(phonemes.subset$Phoneme, function(s) length(grep(segment, s, fixed=TRUE)) > 0, logical(1));
}
is.variant.of <- cmpfun(is.variant.of);

# For a given set of feature values, extract the segments mathing OR between values (return a logical vector referring to the phonemes.subset's rows)
# the feature.values argument contains both the feature and the values and supports two formats:
# 1. + - or 0 followed immediately by the feature name, or
# 2. the feature name followed by : and the values separated by ,
`.` <- function(phonemes.subset, feature.values)
{
  # Parse the feature.values complex:
  if( substr(feature.values,1,1) %in% c("+","-","0") )
  {
    # Format (1):
    feature <- str_trim(substr(feature.values,2,nchar(feature.values)));
    values <- str_trim(substr(feature.values,1,1));
  } else
  {
    # Format (2):
    feature <- strsplit(feature.values,":",fixed=TRUE)[[1]];
    values <- str_trim(strsplit(feature[2],",",fixed=TRUE)[[1]]);
    feature <- str_trim(feature[1]);
  }
  # Get the individual matches:
  f <- sapply(values, function(v) find.matching.phonemes(phonemes.subset, feature=feature,value=v ) );
  # Combine them (if more than one):
  f <- (rowSums(f) > 0); names(f) <- phonemes.subset$Phoneme;
  f;
}
`.` <- cmpfun(`.`);


############################################################################################################################################################################
#
# Define the features and how they are computed.
#
# Use as a list of functions of parameter "x", the subset of phonemes to work on.
# The features have the same name in the two systems but suffix "_F" for Fonetikode system and "_P" for Phoible system.
# Each such function returns a named logical vector corresponding to x's rows and whose names are the segments (the segment is to beincluded in the count only if TRUE).
#
############################################################################################################################################################################

## Feature names:
## Fonetikode: "Phoneme" "GC" "VV" "VH" "VM" "CP" "CM" "CS" "Phon" "Init" "Pri" "Sec" "Pros" "Tone"
## Phoible:    "Phoneme" "tone" "stress" "syll" "short" "long" "cons" "sonorant" "cont" "delayRel" "approx" "tap" "trill" "nasal" "lateral" "labial" "round" "labiodent" "coronal" "anterior" "distrib" "strident" "dorsal" "high" "low" "front" "back" "tense" "rtr" "atr" "perGlotSrc" "epilarSrc" "spreadGlot" "constrGlot" "fortis" "raisedLarynxEject" "loweredLarynxImpl" "click"

# Define the functions for identifying the various classes of segments.
# Most return a logical vector named with the segments in the given inventory x, where TRUE means that the segment belongs to that cathegory.
# The naming convention is .cfv_{NAME}_{SUFFIX} where NAME is the category name and SUFFIX is F for Fonetikode and P for Phoible systems, respectively
# Put all these function names in a list for easy usage:
feature.defs <- NULL;

# all segments, excluding tone:
feature.defs <- c(feature.defs, "segments"=".cfv_segments");
.cfv_segments_F <- cmpfun( function(x){ .(x,"GC:c,v"); } )
.cfv_segments_P <- cmpfun( function(x){ .(x,"0tone"); } )

# vowel system (general features):
feature.defs <- c(feature.defs, "vowels"=".cfv_vowels");
.cfv_vowels_F <- cmpfun( function(x){ .(x,"GC:v"); } )
.cfv_vowels_P <- cmpfun( function(x){ .(x,"+syll") & .(x,"-cons") & .(x,"+sonorant"); } )

feature.defs <- c(feature.defs, "monophtongs"=".cfv_monophtongs");
.cfv_monophtongs_F <- cmpfun( function(x){ .cfv_vowels_F(x) & vapply(unique.feat.vals(x, "VV"), function(s) length(s)==1, logical(1)); } )
.cfv_monophtongs_P <- cmpfun( function(x){ .cfv_vowels_P(x) & vapply(unique.feat.vals(x, "high"), function(s) (length(s)==1 & length(setdiff(s, c("+","-")))==0), logical(1)); } )

feature.defs <- c(feature.defs, "diphtongs"=".cfv_diphtongs");
.cfv_diphtongs_F <- cmpfun( function(x){ .cfv_vowels_F(x) & vapply(unique.feat.vals(x, "VV"), function(s) length(s)==2, logical(1)); } )
.cfv_diphtongs_P <- cmpfun( function(x){ .cfv_vowels_P(x) & vapply(unique.feat.vals(x, "high"), function(s) (length(s)==2 & length(setdiff(s, c("+","-")))==0), logical(1)); } )

feature.defs <- c(feature.defs, "triphtongs"=".cfv_triphtongs");
.cfv_triphtongs_F <- cmpfun( function(x){ .cfv_vowels_F(x) & vapply(unique.feat.vals(x, "VV"), function(s) length(s)==3, logical(1)); } )
.cfv_triphtongs_P <- cmpfun( function(x){ .cfv_vowels_P(x) & vapply(unique.feat.vals(x, "high"), function(s) (length(s)==3 & length(setdiff(s, c("+","-")))==0), logical(1)); } )

# for all vowels:
feature.defs <- c(feature.defs, "heights.v"=".cfv_heights.v");
.cfv_heights.v_F <- cmpfun( function(x, filter=.cfv_vowels_F)
{ 
  y <- filter(x);
  c("c"=any(y & .(x,"VV:c")), 
    "nc"=any(y & .(x,"VV:nc")), 
    "cm"=any(y & .(x,"VV:cm")), 
    "m"=any(y & .(x,"VV:m")), 
    "om"=any(y & .(x,"VV:om")), 
    "no"=any(y & .(x,"VV:no")), 
    "o"=any(y & .(x,"VV:o")));
} )
.cfv_heights.v_P <- cmpfun( function(x, filter=.cfv_vowels_P)
{
  y <- filter(x);
  cases <- as.matrix(expand.grid("high"=c("+","-"),"low"=c("+","-"),"tense"=c("+","-","0"))); 
  z <- vapply(1:nrow(cases), function(k) any(y & 
                                               .(x,paste0(cases[k,"high"],"high")) & 
                                               .(x,paste0(cases[k,"low"],"low")) & 
                                               .(x,paste0(cases[k,"tense"],"tense"))), 
              logical(1)); 
  names(z) <- vapply(1:nrow(cases), function(k) paste0(cases[k,],colnames(cases),collapse=""), character(1)); 
  z;
} )

feature.defs <- c(feature.defs, "lengths.v"=".cfv_lengths.v");
.cfv_lengths.v_F <- cmpfun( function(x, filter=.cfv_vowels_F)
{
  y <- filter(x);
  c("brev"=any(y & .(x,"Pros:brev")), 
    "hl"=any(y & .(x,"Pros:hl")), 
    "long"=any(y & .(x,"Pros:long")), 
    "none"=any(y & .(x,"Pros:none")));
} )
.cfv_lengths.v_P <- cmpfun( function(x, filter=.cfv_vowels_P)
{
  y <- filter(x);
  cases <- as.matrix(expand.grid("short"=c("+","-"),"long"=c("+","-"))); 
  z <- vapply(1:nrow(cases), function(k) any(y & 
                                               .(x,paste0(cases[k,"short"],"short")) & 
                                               .(x,paste0(cases[k,"long"],"long"))), 
              logical(1)); 
  names(z) <- vapply(1:nrow(cases), function(k) paste0(cases[k,],colnames(cases),collapse=""), character(1)); 
  z;
} )

feature.defs <- c(feature.defs, "long.v"=".cfv_long.v");
.cfv_long.v_F <- cmpfun( function(x, filter=.cfv_vowels_F){ filter(x) & .(x,"Pros:long"); } )
.cfv_long.v_P <- cmpfun( function(x, filter=.cfv_vowels_P){ filter(x) & .(x,"+long"); } )

feature.defs <- c(feature.defs, "nasal.v"=".cfv_nasal.v");
.cfv_nasal.v_F <- cmpfun( function(x, filter=.cfv_vowels_F){ filter(x) & .(x,"VM:n,nr,un,nu,nur,nru"); } )
.cfv_nasal.v_P <- cmpfun( function(x, filter=.cfv_vowels_P){ filter(x) & .(x,"+nasal"); } )

feature.defs <- c(feature.defs, "round.v"=".cfv_round.v");
.cfv_round.v_F <- cmpfun( function(x, filter=.cfv_vowels_F){ filter(x) & .(x,"VM:r,nr,ur,ru,nur,nru"); } )
.cfv_round.v_P <- cmpfun( function(x, filter=.cfv_vowels_P){ filter(x) & .(x,"+round"); } )

feature.defs <- c(feature.defs, "high.v"=".cfv_high.v");
.cfv_high.v_F <- cmpfun( function(x, filter=.cfv_vowels_F){ filter(x) & .(x,"VV:c,nc"); } )
.cfv_high.v_P <- cmpfun( function(x, filter=.cfv_vowels_P){ filter(x) & .(x,"+high"); } )

feature.defs <- c(feature.defs, "mid.v"=".cfv_mid.v");
.cfv_mid.v_F <- cmpfun( function(x, filter=.cfv_vowels_F){ filter(x) & .(x,"VV:cm,m,om"); } )
.cfv_mid.v_P <- cmpfun( function(x, filter=.cfv_vowels_P){ filter(x) & .(x,"-high") & .(x,"-low"); } )

feature.defs <- c(feature.defs, "low.v"=".cfv_low.v");
.cfv_low.v_F <- cmpfun( function(x, filter=.cfv_vowels_F){ filter(x) & .(x,"VV:o,no"); } )
.cfv_low.v_P <- cmpfun( function(x, filter=.cfv_vowels_P){ filter(x) & .(x,"+low"); } )

feature.defs <- c(feature.defs, "front.v"=".cfv_front.v");
.cfv_front.v_F <- cmpfun( function(x, filter=.cfv_vowels_F){ filter(x) & .(x,"VH:f,nf"); } )
.cfv_front.v_P <- cmpfun( function(x, filter=.cfv_vowels_P){ filter(x) & .(x,"+front") & .(x,"-back"); } )

feature.defs <- c(feature.defs, "back.v"=".cfv_back.v");
.cfv_back.v_F <- cmpfun( function(x, filter=.cfv_vowels_F){ filter(x) & .(x,"VH:b,nb"); } )
.cfv_back.v_P <- cmpfun( function(x, filter=.cfv_vowels_P){ filter(x) & .(x,"-front") & .(x,"+back"); } )

feature.defs <- c(feature.defs, "tense.v"=".cfv_tense.v");
.cfv_tense.v_F <- cmpfun( function(x, filter=.cfv_vowels_F){ filter(x) & .(x,"VV:c,cm"); } )
.cfv_tense.v_P <- cmpfun( function(x, filter=.cfv_vowels_P){ filter(x) & .(x,"+tense"); } )

feature.defs <- c(feature.defs, "lax.v"=".cfv_lax.v");
.cfv_lax.v_F <- cmpfun( function(x, filter=.cfv_vowels_F){ filter(x) & .(x,"VV:om,nc,no,o"); } )
.cfv_lax.v_P <- cmpfun( function(x, filter=.cfv_vowels_P){ filter(x) & (.(x,"-tense") | .(x,"0tense")); } )

feature.defs <- c(feature.defs, "atr.v"=".cfv_atr.v");
.cfv_atr.v_F <- cmpfun( function(x, filter=.cfv_vowels_F){ filter(x) & .(x,"Pri:adv"); } )
.cfv_atr.v_P <- cmpfun( function(x, filter=.cfv_vowels_P){ filter(x) & .(x,"+atr"); } )

feature.defs <- c(feature.defs, "rtr.v"=".cfv_rtr.v");
.cfv_rtr.v_F <- cmpfun( function(x, filter=.cfv_vowels_F){ filter(x) & (.(x,"Sec:ph") | .(x,"Pri:ret")); } )
.cfv_rtr.v_P <- cmpfun( function(x, filter=.cfv_vowels_P){ filter(x) & .(x,"+rtr"); } )

feature.defs <- c(feature.defs, "raised.v"=".cfv_raised.v");
.cfv_raised.v_F <- cmpfun( function(x, filter=.cfv_vowels_F){ filter(x) & .cfv_high.v_F(x) & .cfv_back.v_F(x); } )
.cfv_raised.v_P <- cmpfun( function(x, filter=.cfv_vowels_P){ filter(x) & .(x,"+back") & .(x,"+high"); } )

feature.defs <- c(feature.defs, "retracted.v"=".cfv_retracted.v");
.cfv_retracted.v_F <- cmpfun( function(x, filter=.cfv_vowels_F){ filter(x) & .cfv_low.v_F(x) & .cfv_back.v_F(x); } )
.cfv_retracted.v_P <- cmpfun( function(x, filter=.cfv_vowels_P){ filter(x) & .(x,"+back") & .(x,"+low"); } )

feature.defs <- c(feature.defs, "fronted.v"=".cfv_fronted.v");
.cfv_fronted.v_F <- cmpfun( function(x, filter=.cfv_vowels_F){ filter(x) & .cfv_front.v_F(x); } )
.cfv_fronted.v_P <- cmpfun( function(x, filter=.cfv_vowels_P){ filter(x) & .(x,"+front"); } )

feature.defs <- c(feature.defs, "glottalized.v"=".cfv_glottalized.v");
.cfv_glottalized.v_F <- cmpfun( function(x, filter=.cfv_vowels_F){ filter(x) & .(x,"Sec:glt"); } )
.cfv_glottalized.v_P <- cmpfun( function(x, filter=.cfv_vowels_P){ filter(x) & .(x,"+constrGlot"); } )

feature.defs <- c(feature.defs, "laryngealized.v"=".cfv_laryngealized.v");
.cfv_laryngealized.v_F <- cmpfun( function(x, filter=.cfv_vowels_F){ filter(x) & .(x,"Phon:c"); } )
.cfv_laryngealized.v_P <- cmpfun( function(x, filter=.cfv_vowels_P){ NULL; } )

# vowel qualities:
feature.defs <- c(feature.defs, "unique.v"=".cfv_unique.v");
.cfv_unique.v_F <- cmpfun( function(x, filter=.cfv_vowels_F)
{
  y <- filter(x); 
  cases <- as.matrix(expand.grid("VH"=c("c","f","b","v","nf","nb"),"VV"=c("o","no","om","cm","m","c","nc"))); 
  z <- vapply(1:nrow(cases), function(k) any(y & 
                                               .(x,paste0("VH:",cases[k,"VH"])) & 
                                               .(x,paste0("VV:",cases[k,"VV"]))), 
              logical(1)); 
  names(z) <- vapply(1:nrow(cases), function(k) paste0(colnames(cases),":",cases[k,],collapse=" "), character(1)); 
  z;
} )
.cfv_unique.v_P <- cmpfun( function(x, filter=.cfv_vowels_P)
{
  y <- filter(x); 
  cases <- as.matrix(expand.grid("high"=c("+","-"),"low"=c("+","-"),"front"=c("+","-"),"back"=c("+","-"),"tense"=c("+","-","0"))); 
  z <- vapply(1:nrow(cases), function(k) any(y & 
                                               .(x,paste0(cases[k,"high"],"high")) & 
                                               .(x,paste0(cases[k,"low"],"low")) & 
                                               .(x,paste0(cases[k,"front"],"front")) & 
                                               .(x,paste0(cases[k,"back"],"back")) & 
                                               .(x,paste0(cases[k,"tense"],"tense"))), 
              logical(1)); 
  names(z) <- vapply(1:nrow(cases), function(k) paste0(cases[k,],colnames(cases),collapse=""), character(1)); 
  z;
} )

feature.defs <- c(feature.defs, "unique.nasal.v"=".cfv_unique.nasal.v");
.cfv_unique.nasal.v_F <- cmpfun( function(x, filter=.cfv_vowels_F)
{
  y <- filter(x) & .cfv_nasal.v_F(x);  
  cases <- as.matrix(expand.grid("VH"=c("c","f","b","v","nf","nb"),"VV"=c("o","no","om","cm","m","c","nc"))); 
  z <- vapply(1:nrow(cases), function(k) any(y & 
                                               .(x,paste0("VH:",cases[k,"VH"])) & 
                                               .(x,paste0("VV:",cases[k,"VV"])) &
                                               .(x,"VM:n,nr,un,nu,nur,nru")), 
              logical(1)); 
  names(z) <- vapply(1:nrow(cases), function(k) paste0(colnames(cases),":",cases[k,],collapse=" "), character(1)); 
  z;
} )
.cfv_unique.nasal.v_P <- cmpfun( function(x, filter=.cfv_vowels_P)
{
  y <- filter(x) & .cfv_nasal.v_P(x); 
  cases <- as.matrix(expand.grid("high"=c("+","-"),"low"=c("+","-"),"front"=c("+","-"),"back"=c("+","-"),"tense"=c("+","-","0"))); 
  z <- vapply(1:nrow(cases), function(k) any(y & 
                                               .(x,paste0(cases[k,"high"],"high")) & 
                                               .(x,paste0(cases[k,"low"],"low")) & 
                                               .(x,paste0(cases[k,"front"],"front")) & 
                                               .(x,paste0(cases[k,"back"],"back")) & 
                                               .(x,paste0(cases[k,"tense"],"tense"))), 
              logical(1)); 
  names(z) <- vapply(1:nrow(cases), function(k) paste0(cases[k,],colnames(cases),collapse=""), character(1)); 
  z;
} )

# automatically create the equivalent functions for mono-, di- and tri-phtongs:
for( f in c("heights", "lengths", "long", "nasal", "round", "high", "mid", "low", "front", "back", "tense", "lax", "atr", "rtr", "raised", "retracted", "fronted", "glottalized", "laryngealized", "unique", "unique.nasal") )
{
  for( m in c("mono", "di", "tri") )
  {
    feature.defs <- c(feature.defs, paste0(".cfv_",f,"_",m,".v")); names(feature.defs)[length(feature.defs)] <- paste0(f,"_",m,".v");
    for( s in c("_F", "_P") )
    {
      eval(parse(text=paste0(".cfv_",f,"_",m,".v",s," <- cmpfun( function(x) ", ".cfv_",f,".v",s,"(x, .cfv_", m,"phtongs",s, ") )")));
    }
  }
}

# consonants:
feature.defs <- c(feature.defs, "consonants"=".cfv_consonants");
.cfv_consonants_F <- cmpfun( function(x){ .(x,"GC:c"); } )
.cfv_consonants_P <- cmpfun( function(x){ !.(x,"0click"); } ) # .(x,"+cons");

# place of articulation:
feature.defs <- c(feature.defs, "places.c"=".cfv_places.c");
.cfv_places.c_F <- cmpfun( function(x)
{
  y <- .cfv_consonants_F(x); 
  c("b"=any(y & .(x,"CP:b")), "bld"=any(y & .(x,"CP:bld")), "ba"=any(y & .(x,"CP:ba")), "bpa"=any(y & .(x,"CP:bpa")),
    "ld"=any(y & .(x,"CP:ld")), "lv"=any(y & .(x,"CP:lv")), "lu"=any(y & .(x,"CP:lu")), "ll"=any(y & .(x,"CP:ll")),
    "i"=any(y & .(x,"CP:i")), "d"=any(y & .(x,"CP:d")), "a"=any(y & .(x,"CP:a")), "pa"=any(y & .(x,"CP:pa")),
    "r"=any(y & .(x,"CP:r")), "dv"=any(y & .(x,"CP:dv")), "av"=any(y & .(x,"CP:av")), "ap"=any(y & .(x,"CP:ap")),
    "p"=any(y & .(x,"CP:p")), "pav"=any(y & .(x,"CP:pav")), "v"=any(y & .(x,"CP:v")), "u"=any(y & .(x,"CP:u")),
    "ph"=any(y & .(x,"CP:ph")), "e"=any(y & .(x,"CP:e")), "g"=any(y & .(x,"CP:g")));
} )          
.cfv_places.c_P <- cmpfun( function(x)
{ 
  c("bilabial"=any(.cfv_bilabial.c_P(x)), "labiodental"=any(.cfv_labiodental.c_P(x)), "dental" = any(.cfv_dental.c_P(x)),
    "alveolar" = any(.cfv_alveolar.c_P(x)), "palatoalveolar" = any(.cfv_palatoalveolar.c_P(x)), "alveolopalatal" = any(.cfv_alveolopalatal.c_P(x)),
    "postalveolar" = any(.cfv_postalveolar.c_P(x)), "true_retroflex" = any(.cfv_true_retroflex.c_P(x)), "palatal" = any(.cfv_palatal.c_P(x)),
    "velar" = any(.cfv_velar.c_P(x)), "uvular" = any(.cfv_uvular.c_P(x)), "pharyngeal_epiglottal" = any(.cfv_pharyngeal_epiglottal.c_P(x)),
    "glottal" = any(.cfv_glottal.c_P(x)));
} )

feature.defs <- c(feature.defs, "bilabial.c"=".cfv_bilabial.c");
.cfv_bilabial.c_F <- cmpfun( function(x){ .(x,"GC:c") & .(x,"CP:b"); } )
.cfv_bilabial.c_P <- cmpfun( function(x){ .(x,"-syll") & .(x,"+labial") & .(x,"-labiodent") & .(x,"-dorsal"); } )

feature.defs <- c(feature.defs, "labiodental.c"=".cfv_labiodental.c");
.cfv_labiodental.c_F <- cmpfun( function(x){ .(x,"GC:c") & .(x,"CP:ld"); } )
.cfv_labiodental.c_P <- cmpfun( function(x){ .(x,"-syll") & .(x,"+labial") & .(x,"+labiodent") & .(x,"-dorsal"); } )

feature.defs <- c(feature.defs, "double_articulated.c"=".cfv_double_articulated.c");
.cfv_double_articulated.c_F <- cmpfun( function(x){ .(x,"GC:c") & .(x,"CP:lv,lu,ll,dv,av,bld,pav,ba,bpa"); } )
.cfv_double_articulated.c_P <- cmpfun( function(x){ NULL; } )

feature.defs <- c(feature.defs, "dental.c"=".cfv_dental.c");
.cfv_dental.c_F <- cmpfun( function(x){ .(x,"GC:c") & .(x,"CP:d,i"); } )
.cfv_dental.c_P <- cmpfun( function(x){ .(x,"-syll") & .(x,"0labiodent") & .(x,"+coronal") & .(x,"+anterior") & .(x,"+distrib"); } )

feature.defs <- c(feature.defs, "alveolar.c"=".cfv_alveolar.c");
.cfv_alveolar.c_F <- cmpfun( function(x){ .(x,"GC:c") & .(x,"CP:a"); } )
.cfv_alveolar.c_P <- cmpfun( function(x){ .(x,"-syll") & .(x,"0labiodent") & .(x,"+coronal") & .(x,"+anterior") & .(x,"-distrib"); } )

feature.defs <- c(feature.defs, "palatoalveolar.c"=".cfv_palatoalveolar.c");
.cfv_palatoalveolar.c_F <- cmpfun( function(x){ .(x,"GC:c") & .(x,"CP:pa"); } )
.cfv_palatoalveolar.c_P <- cmpfun( function(x){ .(x,"-syll") & .(x,"0labiodent") & .(x,"+coronal") & .(x,"-anterior") & .(x,"+distrib") & .(x,"+strident") & .(x,"-dorsal"); } )

feature.defs <- c(feature.defs, "alveolopalatal.c"=".cfv_alveolopalatal.c");
.cfv_alveolopalatal.c_F <- cmpfun( function(x){ .(x,"GC:c") & .(x,"CP:ap"); } )
.cfv_alveolopalatal.c_P <- cmpfun( function(x){ .(x,"-syll") & .(x,"0labiodent") & .(x,"+coronal") & .(x,"+anterior") & .(x,"+distrib") & .(x,"+strident") & .(x,"+dorsal"); } )

feature.defs <- c(feature.defs, "postalveolar.c"=".cfv_postalveolar.c");
.cfv_postalveolar.c_F <- cmpfun( function(x){ .(x,"GC:c") & .(x,"CP:a") & .(x,"Pri:ret"); } )
.cfv_postalveolar.c_P <- cmpfun( function(x){ .(x,"-syll") & .(x,"0labiodent") & .(x,"+coronal") & .(x,"-anterior") & .(x,"+distrib") & .(x,"-strident") & .(x,"-dorsal"); } )

feature.defs <- c(feature.defs, "true_retroflex.c"=".cfv_true_retroflex.c");
.cfv_true_retroflex.c_F <- cmpfun( function(x){ .(x,"GC:c") & .(x,"CP:r"); } )
.cfv_true_retroflex.c_P <- cmpfun( function(x){ .(x,"-syll") & .(x,"0labiodent") & .(x,"+coronal") & .(x,"-anterior") & .(x,"-distrib"); } )

feature.defs <- c(feature.defs, "palatal.c"=".cfv_palatal.c");
.cfv_palatal.c_F <- cmpfun( function(x){ .(x,"GC:c") & .(x,"CP:p"); } )
.cfv_palatal.c_P <- cmpfun( function(x){ .(x,"-syll") & .(x,"0labiodent") & .(x,"+coronal") & .(x,"-anterior") & .(x,"+distrib") & .(x,"+dorsal") & .(x,"-strident") | (is.variant.of(x,"j") | is.variant.of(x,"ɥ")); } )

feature.defs <- c(feature.defs, "velar.c"=".cfv_velar.c");
.cfv_velar.c_F <- cmpfun( function(x){ .(x,"GC:c") & .(x,"CP:v"); } )
.cfv_velar.c_P <- cmpfun( function(x){ .(x,"-syll") & .(x,"0labiodent") & .(x,"-coronal") & .(x,"+dorsal") & .(x,"+high") & .(x,"-low") & !.(x,"0click") & ifelse(.(x,"+front"), .(x,"+cons") & .(x,"+back"), TRUE) & ifelse(.(x,"+constrGlot"), .(x,"+raisedLarynxEject"), TRUE) | is.variant.of(x,"w") | is.variant.of(x,"ʍ") | is.variant.of(x,"ɰ"); } )

feature.defs <- c(feature.defs, "uvular.c"=".cfv_uvular.c");
.cfv_uvular.c_F <- cmpfun( function(x){ .(x,"GC:c") & .(x,"CP:u"); } )
.cfv_uvular.c_P <- cmpfun( function(x){ .(x,"-syll") & .(x,"0labiodent") & .(x,"-coronal") & .(x,"+dorsal") & .(x,"-high") & .(x,"-low") & !.(x,"0click"); } )

feature.defs <- c(feature.defs, "pharyngeal_epiglottal.c"=".cfv_pharyngeal_epiglottal.c");
.cfv_pharyngeal_epiglottal.c_F <- cmpfun( function(x){ .(x,"GC:c") & .(x,"CP:ph,e"); } )
.cfv_pharyngeal_epiglottal.c_P <- cmpfun( function(x){ .(x,"-syll") & .(x,"0labiodent") & .(x,"-coronal") & .(x,"+dorsal") & .(x,"-high") & .(x,"+low"); } )

feature.defs <- c(feature.defs, "glottal.c"=".cfv_glottal.c");
.cfv_glottal.c_F <- cmpfun( function(x){ .(x,"GC:c") & .(x,"CP:g"); } )
.cfv_glottal.c_P <- cmpfun( function(x){ .(x,"0labiodent") & .(x,"-coronal") & .(x,"-dorsal") & .(x,"-epilarSrc"); } )

# major place classes: 
feature.defs <- c(feature.defs, "labial.c"=".cfv_labial.c");
.cfv_labial.c_F <- cmpfun( function(x){ .(x,"GC:c") & .(x,"CP:b,ld,lv,lu"); } )
.cfv_labial.c_P <- cmpfun( function(x){ .(x,"-syll") & .(x,"+labial") & .(x,"-coronal") & .(x,"-dorsal") & !.(x,"0click"); } )

feature.defs <- c(feature.defs, "coronal.c"=".cfv_coronal.c");
.cfv_coronal.c_F <- cmpfun( function(x){ .(x,"GC:c") & .(x,"CP:d,i,a,pa,ap,r"); } )
.cfv_coronal.c_P <- cmpfun( function(x){ .(x,"-syll") & .(x,"0labiodent") & .(x,"-labial") & .(x,"+coronal") & .(x,"-dorsal") & !.(x,"0click"); } )

feature.defs <- c(feature.defs, "dorsal.c"=".cfv_dorsal.c");
.cfv_dorsal.c_F <- cmpfun( function(x){ .(x,"GC:c") & .(x,"CP:p,v,u"); } )
.cfv_dorsal.c_P <- cmpfun( function(x){ .(x,"-syll") & .(x,"0labiodent") & .(x,"-coronal") & .(x,"+dorsal") & .(x,"-low") & !.(x,"0click"); } )

feature.defs <- c(feature.defs, "guttural.c"=".cfv_guttural.c");
.cfv_guttural.c_F <- cmpfun( function(x){ .(x,"GC:c") & .(x,"CP:ph,e,g"); } )
.cfv_guttural.c_P <- cmpfun( function(x){ .cfv_pharyngeal_epiglottal.c_P(x) | .cfv_glottal.c_P(x); } )

# manner: 
feature.defs <- c(feature.defs, "manners.c"=".cfv_manners.c");
.cfv_manners.c_F <- cmpfun( function(x)
{ 
  c("stop" = any(.cfv_stop.c_F(x)), "fricative" = any(.cfv_fricative.c_F(x)), "affricate" = any(.cfv_affricate.c_F(x)), 
    "nasal" = any(.cfv_nasal.c_F(x)), "approximant" = any(.cfv_approximant.c_F(x)), "click" = any(.cfv_click_F(x)));
} )
.cfv_manners.c_P <- cmpfun( function(x)
{
  c("stop" = any(.cfv_stop.c_P(x)), "fricative" = any(.cfv_fricative.c_P(x)), "affricate" = any(.cfv_affricate.c_P(x)),
    "nasal" = any(.cfv_nasal.c_P(x)), "approximant" = any(.cfv_approximant.c_P(x)), "click" = any(.cfv_click_P(x)));
} )

feature.defs <- c(feature.defs, "obstruent.c"=".cfv_obstruent.c");
.cfv_obstruent.c_F <- cmpfun( function(x){ .(x,"GC:c") & .(x,"CM:s,f,af"); } )
.cfv_obstruent.c_P <- cmpfun( function(x){ .(x,"+cons") & .(x,"-sonorant") & .(x,"-approx"); } )

feature.defs <- c(feature.defs, "voiced_obstruent.c"=".cfv_voiced_obstruent.c");
.cfv_voiced_obstruent.c_F <- cmpfun( function(x){ .(x,"GC:c") & .(x,"CM:s,f,af") & .(x,"Phon:vd,b,c"); } )
.cfv_voiced_obstruent.c_P <- cmpfun( function(x){ .(x,"-sonorant") & .(x,"-approx") & .(x,"+perGlotSrc"); } )

feature.defs <- c(feature.defs, "voiceless_obstruent.c"=".cfv_voiceless_obstruent.c");
.cfv_voiceless_obstruent.c_F <- cmpfun( function(x){ .(x,"GC:c") & .(x,"CM:s,f,af") & .(x,"Phon:vl"); } )
.cfv_voiceless_obstruent.c_P <- cmpfun( function(x){ .(x,"-sonorant") & .(x,"-approx") & .(x,"-perGlotSrc"); } )

feature.defs <- c(feature.defs, "aspirated_obstruent.c"=".cfv_aspirated_obstruent.c");
.cfv_aspirated_obstruent.c_F <- cmpfun( function(x){ .(x,"GC:c") & .(x,"CM:s,f,af") & .(x,"CS:pra,poa,prag,poag"); } )
.cfv_aspirated_obstruent.c_P <- cmpfun( function(x){ .(x,"+cons") & .(x,"-sonorant") & .(x,"-approx") & .(x,"+spreadGlot") & .(x, "-perGlotSrc") & .(x,"-loweredLarynxImpl"); } )

feature.defs <- c(feature.defs, "glottalized_obstruent.c"=".cfv_glottalized_obstruent.c");
.cfv_glottalized_obstruent.c_F <- cmpfun( function(x){ .(x,"GC:c") & .(x,"CM:s,f,af") & (.(x,"Phon:c") | .(x,"Init:ge,gi")); } )
.cfv_glottalized_obstruent.c_P <- cmpfun( function(x){ .(x,"-sonorant") & .(x,"-approx") & .(x,"-perGlotSrc") & .(x,"+constrGlot"); } )

feature.defs <- c(feature.defs, "stop.c"=".cfv_stop.c");
.cfv_stop.c_F <- cmpfun( function(x){ .(x,"GC:c") & .(x,"CM:s"); } )
.cfv_stop.c_P <- cmpfun( function(x){ .(x,"+cons") & .(x,"-sonorant") & .(x,"-approx") & .(x,"-cont") & .(x,"-delayRel"); } )

feature.defs <- c(feature.defs, "voiced_stop.c"=".cfv_voiced_stop.c");
.cfv_voiced_stop.c_F <- cmpfun( function(x){ .(x,"GC:c") & .(x,"CM:s") & .(x,"Phon:vd,b,c"); } )
.cfv_voiced_stop.c_P <- cmpfun( function(x){ .(x,"+cons") & .(x,"-sonorant") & .(x,"-approx") & .(x,"-cont") & .(x,"-delayRel") & .(x,"+perGlotSrc"); } )

feature.defs <- c(feature.defs, "voiceless_stop.c"=".cfv_voiceless_stop.c");
.cfv_voiceless_stop.c_F <- cmpfun( function(x){ .(x,"GC:c") & .(x,"CM:s") & .(x,"Phon:vl"); } )
.cfv_voiceless_stop.c_P <- cmpfun( function(x){ .(x,"+cons") & .(x,"-sonorant") & .(x,"-approx") & .(x,"-cont") & .(x,"-delayRel") & .(x,"-perGlotSrc"); } )

feature.defs <- c(feature.defs, "aspirated_stop.c"=".cfv_aspirated_stop.c");
.cfv_aspirated_stop.c_F <- cmpfun( function(x){ .(x,"GC:c") & .(x,"CS:pra,poa,prag,poag"); } )
.cfv_aspirated_stop.c_P <- cmpfun( function(x){ .(x,"+cons") & .(x,"-sonorant") & .(x,"-approx") & .(x,"-cont") & .(x,"-delayRel") & .(x,"-perGlotSrc") & .(x,"+spreadGlot") & .(x,"-loweredLarynxImpl"); } )

feature.defs <- c(feature.defs, "glottalized_stop.c"=".cfv_glottalized_stop.c");
.cfv_glottalized_stop.c_F <- cmpfun( function(x){ .(x,"GC:c") & .(x,"CM:s") & .(x,"Init:ge,gi"); } )
.cfv_glottalized_stop.c_P <- cmpfun( function(x){ .(x,"+cons") & .(x,"-sonorant") & .(x,"-approx") & .(x,"-cont") & .(x,"-delayRel") & ((.(x,"+raisedLarynxEject") | .(x,"+loweredLarynxImpl")) | (.(x,"+constrGlot") & !(.(x,"0labiodent") & .(x,"-coronal") & .(x,"-dorsal")))); } )

feature.defs <- c(feature.defs, "fricative.c"=".cfv_fricative.c");
.cfv_fricative.c_F <- cmpfun( function(x){ .(x,"GC:c") & .(x,"CM:f"); } )
.cfv_fricative.c_P <- cmpfun( function(x){ .(x,"-sonorant") & .(x,"-approx") & .(x,"+cont") & .(x,"+delayRel"); } )

feature.defs <- c(feature.defs, "voiced_fricative.c"=".cfv_voiced_fricative.c");
.cfv_voiced_fricative.c_F <- cmpfun( function(x){ .(x,"GC:c") & .(x,"CM:f") & .(x,"Phon:vd,b,c"); } )
.cfv_voiced_fricative.c_P <- cmpfun( function(x){ .(x,"-sonorant") & .(x,"-approx") & .(x,"+cont") & .(x,"+delayRel") & .(x,"+perGlotSrc"); } )

feature.defs <- c(feature.defs, "voiceless_fricative.c"=".cfv_voiceless_fricative.c");
.cfv_voiceless_fricative.c_F <- cmpfun( function(x){ .(x,"GC:c") & .(x,"CM:f") & .(x,"Phon:vl"); } )
.cfv_voiceless_fricative.c_P <- cmpfun( function(x){ .(x,"-sonorant") & .(x,"-approx") & .(x,"+cont") & .(x,"+delayRel") & .(x,"-perGlotSrc"); } )

feature.defs <- c(feature.defs, "affricate.c"=".cfv_affricate.c");
.cfv_affricate.c_F <- cmpfun( function(x){ .(x,"GC:c") & .(x,"CM:af"); } )
.cfv_affricate.c_P <- cmpfun( function(x){ .(x,"-sonorant") & .(x,"-approx") & .(x,"-cont") & .(x,"+delayRel"); } )

feature.defs <- c(feature.defs, "sonorant.c"=".cfv_sonorant.c");
.cfv_sonorant.c_F <- cmpfun( function(x){ .(x,"GC:c") & .(x,"CM:n,a,t,tr"); } )
.cfv_sonorant.c_P <- cmpfun( function(x){ .(x,"+sonorant") & .(x,"-syll") & !.(x,"0click"); } )

feature.defs <- c(feature.defs, "voiced_sonorant.c"=".cfv_voiced_sonorant.c");
.cfv_voiced_sonorant.c_F <- cmpfun( function(x){ .cfv_sonorant.c_F(x) & .(x,"Phon:vd,b,c"); } )
.cfv_voiced_sonorant.c_P <- cmpfun( function(x){ .cfv_sonorant.c_P(x) & .(x,"+perGlotSrc"); } )

feature.defs <- c(feature.defs, "voiceless_sonorant.c"=".cfv_voiceless_sonorant.c");
.cfv_voiceless_sonorant.c_F <- cmpfun( function(x){ .cfv_sonorant.c_F(x) & .(x,"Phon:vl"); } )
.cfv_voiceless_sonorant.c_P <- cmpfun( function(x){ .cfv_sonorant.c_P(x) & .(x,"-perGlotSrc"); } )

feature.defs <- c(feature.defs, "glottalized_resonant.c"=".cfv_glottalized_resonant.c");
.cfv_glottalized_resonant.c_F <- cmpfun( function(x){ .cfv_sonorant.c_F(x) & (.(x,"Phon:c") | .(x,"Init:ge")); } )
.cfv_glottalized_resonant.c_P <- cmpfun( function(x){ .cfv_sonorant.c_P(x) & .(x,"+constrGlot"); } )

feature.defs <- c(feature.defs, "nasal.c"=".cfv_nasal.c");
.cfv_nasal.c_F <- cmpfun( function(x){ .(x,"GC:c") & .(x,"CM:n"); } )
.cfv_nasal.c_P <- cmpfun( function(x){ .(x,"+cons") & .(x,"+sonorant") & .(x,"+nasal"); } )

feature.defs <- c(feature.defs, "approximant.c"=".cfv_approximant.c");
.cfv_approximant.c_F <- cmpfun( function(x){ .(x,"GC:c") & .(x,"CM:a,tr,t"); } )
.cfv_approximant.c_P <- cmpfun( function(x){ .(x,"-syll") & .(x,"+sonorant") & .(x,"+approx") & !.(x,"0click"); } )

feature.defs <- c(feature.defs, "tapflap.c"=".cfv_tapflap.c");
.cfv_tapflap.c_F <- cmpfun( function(x){ .(x,"GC:c") & .(x,"CM:t"); } )
.cfv_tapflap.c_P <- cmpfun( function(x){ .(x,"+tap"); } )

feature.defs <- c(feature.defs, "trill.c"=".cfv_trill.c");
.cfv_trill.c_F <- cmpfun( function(x){ .(x,"GC:c") & .(x,"CM:tr"); } )
.cfv_trill.c_P <- cmpfun( function(x){ .(x,"+trill"); } )

feature.defs <- c(feature.defs, "trill_tap.c"=".cfv_trill_tap.c");
.cfv_trill_tap.c_F <- cmpfun( function(x){ .(x,"GC:c") & .(x,"CM:tr,t"); } )
.cfv_trill_tap.c_P <- cmpfun( function(x){ .(x,"+tap") | .(x,"+trill"); } )

feature.defs <- c(feature.defs, "coronal_trill_tap.c"=".cfv_coronal_trill_tap.c");
.cfv_coronal_trill_tap.c_F <- cmpfun( function(x){ .(x,"GC:c") & .(x,"CP:d,i,a,pa,ap,r") & .(x,"CM:tr,t"); } )
.cfv_coronal_trill_tap.c_P <- cmpfun( function(x){ .(x,"+coronal") & .cfv_trill_tap.c_P(x); } )

feature.defs <- c(feature.defs, "second_articulation.c"=".cfv_second_articulation.c");
.cfv_second_articulation.c_F <- cmpfun( function(x){ .(x,"Sec:w,j,v,ph,jw,jv,wv,wph,wr,jr,lv,lj,lw,lph"); } )
.cfv_second_articulation.c_P <- cmpfun( function(x){ NULL; } )

feature.defs <- c(feature.defs, "glottalized.c"=".cfv_glottalized.c");
.cfv_glottalized.c_F <- cmpfun( function(x){ .(x,"Phon:c") | .(x,"Init:ge,gi"); } )
.cfv_glottalized.c_P <- cmpfun( function(x){ .(x,"+constrGlot"); } )

# UVT vs LVT:
feature.defs <- c(feature.defs, "uvt.c"=".cfv_uvt.c");
.cfv_uvt.c_F <- cmpfun( function(x)
{
  c("bilabial" = any(.cfv_bilabial.c_F(x)), "labiodental" = any(.cfv_labiodental.c_F(x)), "dental" = any(.cfv_dental.c_F(x)),
    "alveolar" = any(.cfv_alveolar.c_F(x)), "palatoalveolar" = any(.cfv_palatoalveolar.c_F(x)), "postalveolar" = any(.cfv_postalveolar.c_F(x)),
    "true_retroflex" = any(.cfv_true_retroflex.c_F(x)), "palatal" = any(.cfv_palatal.c_F(x)), "velar" = any(.cfv_velar.c_F(x)));
} )
.cfv_uvt.c_P <- cmpfun( function(x)
{
  c("bilabial" = any(.cfv_bilabial.c_P(x)), "labiodental" = any(.cfv_labiodental.c_P(x)), "dental" = any(.cfv_dental.c_P(x)),
    "alveolar" = any(.cfv_alveolar.c_P(x)), "palatoalveolar" = any(.cfv_palatoalveolar.c_P(x)), "postalveolar" = any(.cfv_postalveolar.c_P(x)),
    "true_retroflex" = any(.cfv_true_retroflex.c_P(x)), "palatal" = any(.cfv_palatal.c_P(x)), "velar" = any(.cfv_velar.c_P(x)));
} )

feature.defs <- c(feature.defs, "uvt.stops.c"=".cfv_uvt.stops.c");
.cfv_uvt.stops.c_F <- cmpfun( function(x)
{
  c("bilabial" = any(.cfv_bilabial.c_F(x) & .cfv_stop.c_F(x)), "labiodental" = any(.cfv_labiodental.c_F(x) & .cfv_stop.c_F(x)), "dental" = any(.cfv_dental.c_F(x) & .cfv_stop.c_F(x)),
    "alveolar" = any(.cfv_alveolar.c_F(x) & .cfv_stop.c_F(x)), "palatoalveolar" = any(.cfv_palatoalveolar.c_F(x) & .cfv_stop.c_F(x)), "postalveolar" = any(.cfv_postalveolar.c_F(x) & .cfv_stop.c_F(x)),
    "true_retroflex" = any(.cfv_true_retroflex.c_F(x) & .cfv_stop.c_F(x)), "palatal" = any(.cfv_palatal.c_F(x) & .cfv_stop.c_F(x)), "velar" = any(.cfv_velar.c_F(x) & .cfv_stop.c_F(x)));
} )
.cfv_uvt.stops.c_P <- cmpfun( function(x)
{
  c("bilabial" = any(.cfv_bilabial.c_P(x) & .cfv_stop.c_P(x)), "labiodental" = any(.cfv_labiodental.c_P(x) & .cfv_stop.c_P(x)), "dental" = any(.cfv_dental.c_P(x) & .cfv_stop.c_P(x)),
    "alveolar" = any(.cfv_alveolar.c_P(x) & .cfv_stop.c_P(x)), "palatoalveolar" = any(.cfv_palatoalveolar.c_P(x) & .cfv_stop.c_P(x)), "postalveolar" = any(.cfv_postalveolar.c_P(x) & .cfv_stop.c_P(x)),
    "true_retroflex" = any(.cfv_true_retroflex.c_P(x) & .cfv_stop.c_P(x)), "palatal" = any(.cfv_palatal.c_P(x) & .cfv_stop.c_P(x)), "velar" = any(.cfv_velar.c_P(x) & .cfv_stop.c_P(x)));
} )

feature.defs <- c(feature.defs, "uvt.fricatives.c"=".cfv_uvt.fricatives.c");
.cfv_uvt.fricatives.c_F <- cmpfun( function(x)
{
  c("bilabial" = any(.cfv_bilabial.c_F(x) & .cfv_fricative.c_F(x)), "labiodental" = any(.cfv_labiodental.c_F(x) & .cfv_fricative.c_F(x)),
    "dental" = any(.cfv_dental.c_F(x) & .cfv_fricative.c_F(x)), "alveolar" = any(.cfv_alveolar.c_F(x) & .cfv_fricative.c_F(x)),
    "palatoalveolar" = any(.cfv_palatoalveolar.c_F(x) & .cfv_fricative.c_F(x)), "postalveolar" = any(.cfv_postalveolar.c_F(x) & .cfv_fricative.c_F(x)),
    "true_retroflex" = any(.cfv_true_retroflex.c_F(x) & .cfv_fricative.c_F(x)), "palatal" = any(.cfv_palatal.c_F(x) & .cfv_fricative.c_F(x)),
    "velar" = any(.cfv_velar.c_F(x) & .cfv_fricative.c_F(x)));
} )
.cfv_uvt.fricatives.c_P <- cmpfun( function(x)
{
  c("bilabial" = any(.cfv_bilabial.c_P(x) & .cfv_fricative.c_P(x)), "labiodental" = any(.cfv_labiodental.c_P(x) & .cfv_fricative.c_P(x)),
    "dental" = any(.cfv_dental.c_P(x) & .cfv_fricative.c_P(x)), "alveolar" = any(.cfv_alveolar.c_P(x) & .cfv_fricative.c_P(x)),
    "palatoalveolar" = any(.cfv_palatoalveolar.c_P(x) & .cfv_fricative.c_P(x)), "postalveolar" = any(.cfv_postalveolar.c_P(x) & .cfv_fricative.c_P(x)),
    "true_retroflex" = any(.cfv_true_retroflex.c_P(x) & .cfv_fricative.c_P(x)), "palatal" = any(.cfv_palatal.c_P(x) & .cfv_fricative.c_P(x)),
    "velar" = any(.cfv_velar.c_P(x) & .cfv_fricative.c_P(x)));
} )

feature.defs <- c(feature.defs, "uvt.affricates.c"=".cfv_uvt.affricates.c");
.cfv_uvt.affricates.c_F <- cmpfun( function(x)
{
  c("bilabial" = any(.cfv_bilabial.c_F(x) & .cfv_affricate.c_F(x)), "labiodental" = any(.cfv_labiodental.c_F(x) & .cfv_affricate.c_F(x)),
    "dental" = any(.cfv_dental.c_F(x) & .cfv_affricate.c_F(x)), "alveolar" = any(.cfv_alveolar.c_F(x) & .cfv_affricate.c_F(x)),
    "palatoalveolar" = any(.cfv_palatoalveolar.c_F(x) & .cfv_affricate.c_F(x)), "postalveolar" = any(.cfv_postalveolar.c_F(x) & .cfv_affricate.c_F(x)),
    "true_retroflex" = any(.cfv_true_retroflex.c_F(x) & .cfv_affricate.c_F(x)), "palatal" = any(.cfv_palatal.c_F(x) & .cfv_affricate.c_F(x)),
    "velar" = any(.cfv_velar.c_F(x) & .cfv_affricate.c_F(x)));
} )
.cfv_uvt.affricates.c_P <- cmpfun( function(x)
{
  c("bilabial" = any(.cfv_bilabial.c_P(x) & .cfv_affricate.c_P(x)), "labiodental" = any(.cfv_labiodental.c_P(x) & .cfv_affricate.c_P(x)),
    "dental" = any(.cfv_dental.c_P(x) & .cfv_affricate.c_P(x)), "alveolar" = any(.cfv_alveolar.c_P(x) & .cfv_affricate.c_P(x)),
    "palatoalveolar" = any(.cfv_palatoalveolar.c_P(x) & .cfv_affricate.c_P(x)), "postalveolar" = any(.cfv_postalveolar.c_P(x) & .cfv_affricate.c_P(x)),
    "true_retroflex" = any(.cfv_true_retroflex.c_P(x) & .cfv_affricate.c_P(x)), "palatal" = any(.cfv_palatal.c_P(x) & .cfv_affricate.c_P(x)),
    "velar" = any(.cfv_velar.c_P(x) & .cfv_affricate.c_P(x)));
} )

feature.defs <- c(feature.defs, "uvt.nasals.c"=".cfv_uvt.nasals.c");
.cfv_uvt.nasals.c_F <- cmpfun( function(x)
{
  c("bilabial" = any(.cfv_bilabial.c_F(x) & .cfv_nasal.c_F(x)), "labiodental" = any(.cfv_labiodental.c_F(x) & .cfv_nasal.c_F(x)),
    "dental" = any(.cfv_dental.c_F(x) & .cfv_nasal.c_F(x)), "alveolar" = any(.cfv_alveolar.c_F(x) & .cfv_nasal.c_F(x)),
    "palatoalveolar" = any(.cfv_palatoalveolar.c_F(x) & .cfv_nasal.c_F(x)), "postalveolar" = any(.cfv_postalveolar.c_F(x) & .cfv_nasal.c_F(x)),
    "true_retroflex" = any(.cfv_true_retroflex.c_F(x) & .cfv_nasal.c_F(x)), "palatal" = any(.cfv_palatal.c_F(x) & .cfv_nasal.c_F(x)),
    "velar" = any(.cfv_velar.c_F(x) & .cfv_nasal.c_F(x)));
} )
.cfv_uvt.nasals.c_P <- cmpfun( function(x)
{
  c("bilabial" = any(.cfv_bilabial.c_P(x) & .cfv_nasal.c_P(x)), "labiodental" = any(.cfv_labiodental.c_P(x) & .cfv_nasal.c_P(x)),
    "dental" = any(.cfv_dental.c_P(x) & .cfv_nasal.c_P(x)), "alveolar" = any(.cfv_alveolar.c_P(x) & .cfv_nasal.c_P(x)),
    "palatoalveolar" = any(.cfv_palatoalveolar.c_P(x) & .cfv_nasal.c_P(x)), "postalveolar" = any(.cfv_postalveolar.c_P(x) & .cfv_nasal.c_P(x)),
    "true_retroflex" = any(.cfv_true_retroflex.c_P(x) & .cfv_nasal.c_P(x)), "palatal" = any(.cfv_palatal.c_P(x) & .cfv_nasal.c_P(x)),
    "velar" = any(.cfv_velar.c_P(x) & .cfv_nasal.c_P(x)));
} )

feature.defs <- c(feature.defs, "uvt.approximants.c"=".cfv_uvt.approximants.c");
.cfv_uvt.approximants.c_F <- cmpfun( function(x)
{
  c("bilabial" = any(.cfv_bilabial.c_F(x) & .cfv_approximant.c_F(x)), "labiodental" = any(.cfv_labiodental.c_F(x) & .cfv_approximant.c_F(x)),
    "dental" = any(.cfv_dental.c_F(x) & .cfv_approximant.c_F(x)), "alveolar" = any(.cfv_alveolar.c_F(x) & .cfv_approximant.c_F(x)),
    "palatoalveolar" = any(.cfv_palatoalveolar.c_F(x) & .cfv_approximant.c_F(x)), "postalveolar" = any(.cfv_postalveolar.c_F(x) & .cfv_approximant.c_F(x)),
    "true_retroflex" = any(.cfv_true_retroflex.c_F(x) & .cfv_approximant.c_F(x)), "palatal" = any(.cfv_palatal.c_F(x) & .cfv_approximant.c_F(x)),
    "velar" = any(.cfv_velar.c_F(x) & .cfv_approximant.c_F(x)));
} )
.cfv_uvt.approximants.c_P <- cmpfun( function(x)
{
  c("bilabial" = any(.cfv_bilabial.c_P(x) & .cfv_approximant.c_P(x)), "labiodental" = any(.cfv_labiodental.c_P(x) & .cfv_approximant.c_P(x)),
    "dental" = any(.cfv_dental.c_P(x) & .cfv_approximant.c_P(x)), "alveolar" = any(.cfv_alveolar.c_P(x) & .cfv_approximant.c_P(x)),
    "palatoalveolar" = any(.cfv_palatoalveolar.c_P(x) & .cfv_approximant.c_P(x)), "postalveolar" = any(.cfv_postalveolar.c_P(x) & .cfv_approximant.c_P(x)),
    "true_retroflex" = any(.cfv_true_retroflex.c_P(x) & .cfv_approximant.c_P(x)), "palatal" = any(.cfv_palatal.c_P(x) & .cfv_approximant.c_P(x)),
    "velar" = any(.cfv_velar.c_P(x) & .cfv_approximant.c_P(x)));
} )

feature.defs <- c(feature.defs, "uvt.approximants.c"=".cfv_uvt.approximants.c");
.cfv_uvt.approximants.c_F <- cmpfun( function(x)
{
  c("bilabial" = any(.cfv_bilabial.c_F(x) & .cfv_approximant.c_F(x)), "labiodental" = any(.cfv_labiodental.c_F(x) & .cfv_approximant.c_F(x)),
    "dental" = any(.cfv_dental.c_F(x) & .cfv_approximant.c_F(x)), "alveolar" = any(.cfv_alveolar.c_F(x) & .cfv_approximant.c_F(x)),
    "palatoalveolar" = any(.cfv_palatoalveolar.c_F(x) & .cfv_approximant.c_F(x)), "postalveolar" = any(.cfv_postalveolar.c_F(x) & .cfv_approximant.c_F(x)),
    "true_retroflex" = any(.cfv_true_retroflex.c_F(x) & .cfv_approximant.c_F(x)), "palatal" = any(.cfv_palatal.c_F(x) & .cfv_approximant.c_F(x)),
    "velar" = any(.cfv_velar.c_F(x) & .cfv_approximant.c_F(x)));
} )
.cfv_uvt.approximants.c_P <- cmpfun( function(x)
{
  c("bilabial" = any(.cfv_bilabial.c_P(x) & .cfv_approximant.c_P(x)), "labiodental" = any(.cfv_labiodental.c_P(x) & .cfv_approximant.c_P(x)),
    "dental" = any(.cfv_dental.c_P(x) & .cfv_approximant.c_P(x)), "alveolar" = any(.cfv_alveolar.c_P(x) & .cfv_approximant.c_P(x)),
    "palatoalveolar" = any(.cfv_palatoalveolar.c_P(x) & .cfv_approximant.c_P(x)), "postalveolar" = any(.cfv_postalveolar.c_P(x) & .cfv_approximant.c_P(x)),
    "true_retroflex" = any(.cfv_true_retroflex.c_P(x) & .cfv_approximant.c_P(x)), "palatal" = any(.cfv_palatal.c_P(x) & .cfv_approximant.c_P(x)),
    "velar" = any(.cfv_velar.c_P(x) & .cfv_approximant.c_P(x)));
} )

feature.defs <- c(feature.defs, "lvt.c"=".cfv_lvt.c");
.cfv_lvt.c_F <- cmpfun( function(x)
{ 
  c("uvular" = any(.cfv_uvular.c_F(x)), "pharyngeal_epiglottal" = any(.cfv_pharyngeal_epiglottal.c_F(x)), "glottal" = any(.cfv_glottal.c_F(x))); 
} )
.cfv_lvt.c_P <- cmpfun( function(x)
{ 
  c("uvular" = any(.cfv_uvular.c_P(x)), "pharyngeal_epiglottal" = any(.cfv_pharyngeal_epiglottal.c_P(x)), "glottal" = any(.cfv_glottal.c_P(x))); 
} )

feature.defs <- c(feature.defs, "lvt.stops.c"=".cfv_lvt.stops.c");
.cfv_lvt.stops.c_F <- cmpfun( function(x)
{
  c("uvular" = any(.cfv_uvular.c_F(x) & .cfv_stop.c_F(x)), 
    "pharyngeal_epiglottal" = any(.cfv_pharyngeal_epiglottal.c_F(x) & .cfv_stop.c_F(x)), 
    "glottal" = any(.cfv_glottal.c_F(x) & .cfv_stop.c_F(x)));
} )
.cfv_lvt.stops.c_P <- cmpfun( function(x) 
{
  c("uvular" = any(.cfv_uvular.c_P(x) & .cfv_stop.c_P(x)), 
    "pharyngeal_epiglottal" = any(.cfv_pharyngeal_epiglottal.c_P(x) & .cfv_stop.c_P(x)), 
    "glottal" = any(.cfv_glottal.c_P(x) & .cfv_stop.c_P(x)));
} )

feature.defs <- c(feature.defs, "lvt.fricatives.c"=".cfv_lvt.fricatives.c");
.cfv_lvt.fricatives.c_F <- cmpfun( function(x)
{
  c("uvular" = any(.cfv_uvular.c_F(x) & .cfv_fricative.c_F(x)), 
    "pharyngeal_epiglottal" = any(.cfv_pharyngeal_epiglottal.c_F(x) & .cfv_fricative.c_F(x)), 
    "glottal" = any(.cfv_glottal.c_F(x) & .cfv_fricative.c_F(x)));
} )
.cfv_lvt.fricatives.c_P <- cmpfun( function(x)
{
  c("uvular" = any(.cfv_uvular.c_P(x) & .cfv_fricative.c_P(x)), 
    "pharyngeal_epiglottal" = any(.cfv_pharyngeal_epiglottal.c_P(x) & .cfv_fricative.c_P(x)), 
    "glottal" = any(.cfv_glottal.c_P(x) & .cfv_fricative.c_P(x)));
} )

feature.defs <- c(feature.defs, "lvt.affricates.c"=".cfv_lvt.affricates.c");
.cfv_lvt.affricates.c_F <- cmpfun( function(x)
{
  c("uvular" = any(.cfv_uvular.c_F(x) & .cfv_affricate.c_F(x)), 
    "pharyngeal_epiglottal" = any(.cfv_pharyngeal_epiglottal.c_F(x) & .cfv_affricate.c_F(x)), 
    "glottal" = any(.cfv_glottal.c_F(x) & .cfv_affricate.c_F(x)));
} )
.cfv_lvt.affricates.c_P <- cmpfun( function(x)
{
  c("uvular" = any(.cfv_uvular.c_P(x) & .cfv_affricate.c_P(x)), 
    "pharyngeal_epiglottal" = any(.cfv_pharyngeal_epiglottal.c_P(x) & .cfv_affricate.c_P(x)), 
    "glottal" = any(.cfv_glottal.c_P(x) & .cfv_affricate.c_P(x)));
} )

feature.defs <- c(feature.defs, "lvt.nasals.c"=".cfv_lvt.nasals.c");
.cfv_lvt.nasals.c_F <- cmpfun( function(x)
{
  c("uvular" = any(.cfv_uvular.c_F(x) & .cfv_nasal.c_F(x)), 
    "pharyngeal_epiglottal" = any(.cfv_pharyngeal_epiglottal.c_F(x) & .cfv_nasal.c_F(x)), 
    "glottal" = any(.cfv_glottal.c_F(x) & .cfv_nasal.c_F(x)));
} )
.cfv_lvt.nasals.c_P <- cmpfun( function(x)
{
  c("uvular" = any(.cfv_uvular.c_P(x) & .cfv_nasal.c_P(x)), 
    "pharyngeal_epiglottal" = any(.cfv_pharyngeal_epiglottal.c_P(x) & .cfv_nasal.c_P(x)), 
    "glottal" = any(.cfv_glottal.c_P(x) & .cfv_nasal.c_P(x)));
} )

feature.defs <- c(feature.defs, "lvt.approximants.c"=".cfv_lvt.approximants.c");
.cfv_lvt.approximants.c_F <- cmpfun( function(x)
{
  c("uvular" = any(.cfv_uvular.c_F(x) & .cfv_approximant.c_F(x)), 
    "pharyngeal_epiglottal" = any(.cfv_pharyngeal_epiglottal.c_F(x) & .cfv_approximant.c_F(x)), 
    "glottal" = any(.cfv_glottal.c_F(x) & .cfv_approximant.c_F(x)));
} )
.cfv_lvt.approximants.c_P <- cmpfun( function(x)
{
  c("uvular" = any(.cfv_uvular.c_P(x) & .cfv_approximant.c_P(x)), 
    "pharyngeal_epiglottal" = any(.cfv_pharyngeal_epiglottal.c_P(x) & .cfv_approximant.c_P(x)), 
    "glottal" = any(.cfv_glottal.c_P(x) & .cfv_approximant.c_P(x)));
} )

# ratios:
feature.defs <- c(feature.defs, "ratio.voiced.voiceless.obstruents"=".cfv_ratio.voiced.voiceless.obstruents");
.cfv_ratio.voiced.voiceless.obstruents_F <- cmpfun( function(x)
{ 
  x1 <- .cfv_voiced_obstruent.c_F(x);
  x2 <- .cfv_voiceless_obstruent.c_F(x);
  r <- sum(x1) / sum(x2); names(r) <- paste0("( ", paste0(names(x1)[x1],collapse=" "), " ) / ( ", paste0(names(x2)[x2],collapse=" "), " )");
  return (r);
} )
.cfv_ratio.voiced.voiceless.obstruents_P <- cmpfun( function(x)
{ 
  x1 <- .cfv_voiced_obstruent.c_P(x);
  x2 <- .cfv_voiceless_obstruent.c_P(x);
  r <- sum(x1) / sum(x2); names(r) <- paste0("( ", paste0(names(x1)[x1],collapse=" "), " ) / ( ", paste0(names(x2)[x2],collapse=" "), " )");
  return (r);
} )

feature.defs <- c(feature.defs, "ratio.voiced.voiceless.stops"=".cfv_ratio.voiced.voiceless.stops");
.cfv_ratio.voiced.voiceless.stops_F <- cmpfun( function(x)
{ 
  x1 <- .cfv_voiced_stop.c_F(x);
  x2 <- .cfv_voiceless_stop.c_F(x);
  r <- sum(x1) / sum(x2); names(r) <- paste0("( ", paste0(names(x1)[x1],collapse=" "), " ) / ( ", paste0(names(x2)[x2],collapse=" "), " )");
  return (r);
} )
.cfv_ratio.voiced.voiceless.stops_P <- cmpfun( function(x)
{ 
  x1 <- .cfv_voiced_stop.c_P(x);
  x2 <- .cfv_voiceless_stop.c_P(x);
  r <- sum(x1) / sum(x2); names(r) <- paste0("( ", paste0(names(x1)[x1],collapse=" "), " ) / ( ", paste0(names(x2)[x2],collapse=" "), " )");
  return (r);
} )

feature.defs <- c(feature.defs, "ratio.obstruents.sonorants"=".cfv_ratio.obstruents.sonorants");
.cfv_ratio.obstruents.sonorants_F <- cmpfun( function(x)
{
  x1 <- .cfv_obstruent.c_F(x);
  x2 <- .cfv_sonorant.c_F(x);
  r <- sum(x1) / sum(x2); names(r) <- paste0("( ", paste0(names(x1)[x1],collapse=" "), " ) / ( ", paste0(names(x2)[x2],collapse=" "), " )");
  return (r);
} )
.cfv_ratio.obstruents.sonorants_P <- cmpfun( function(x)
{
  x1 <- .cfv_obstruent.c_P(x);
  x2 <- .cfv_sonorant.c_P(x);
  r <- sum(x1) / sum(x2); names(r) <- paste0("( ", paste0(names(x1)[x1],collapse=" "), " ) / ( ", paste0(names(x2)[x2],collapse=" "), " )");
  return (r);
} )

# initiation classes:
feature.defs <- c(feature.defs, "egressive"=".cfv_egressive");
.cfv_egressive_F <- cmpfun( function(x){ .(x,"Init:p"); } )
.cfv_egressive_P <- cmpfun( function(x){ .(x,"-loweredLarynxImpl") & .(x,"-raisedLarynxEject") & (.(x,"-click") | .(x,"0click")); } )

feature.defs <- c(feature.defs, "implosive"=".cfv_implosive");
.cfv_implosive_F <- cmpfun( function(x){ .(x,"Init:gi"); } )
.cfv_implosive_P <- cmpfun( function(x){ .(x,"+loweredLarynxImpl"); } )

feature.defs <- c(feature.defs, "ejective"=".cfv_ejective");
.cfv_ejective_F <- cmpfun( function(x){ .(x,"Init:ge"); } )
.cfv_ejective_P <- cmpfun( function(x){ .(x,"+raisedLarynxEject"); } )

feature.defs <- c(feature.defs, "click"=".cfv_click");
.cfv_click_F <- cmpfun( function(x){ .(x,"Init:vi"); } )
.cfv_click_P <- cmpfun( function(x){ .(x,"+click"); } )

# phonation classes:
feature.defs <- c(feature.defs, "voiceless"=".cfv_voiceless");
.cfv_voiceless_F <- cmpfun( function(x){ .(x,"Phon:vl"); } )
.cfv_voiceless_P <- cmpfun( function(x){ .(x,"-perGlotSrc"); } )

feature.defs <- c(feature.defs, "voiced"=".cfv_voiced");
.cfv_voiced_F <- cmpfun( function(x){ .(x,"Phon:vd"); } )
.cfv_voiced_P <- cmpfun( function(x){ .(x,"+perGlotSrc"); } )

feature.defs <- c(feature.defs, "breathy"=".cfv_breathy");
.cfv_breathy_F <- cmpfun( function(x){ .(x,"Phon:b"); } )
.cfv_breathy_P <- cmpfun( function(x){ .(x,"+perGlotSrc") & .(x,"+spreadGlot"); } )

feature.defs <- c(feature.defs, "creaky"=".cfv_creaky");
.cfv_creaky_F <- cmpfun( function(x){ .(x,"Phon:c"); } )
.cfv_creaky_P <- cmpfun( function(x){ .(x,"+perGlotSrc") & .(x,"+constrGlot"); } )

# tone:
feature.defs <- c(feature.defs, "tones"=".cfv_tones");
.cfv_tones_F <- cmpfun( function(x){ .(x,"GC:ss"); } )
.cfv_tones_P <- cmpfun( function(x){ .(x,"+tone"); } )

feature.defs <- c(feature.defs, "level_tones"=".cfv_level_tones");
.cfv_level_tones_F <- cmpfun( function(x){ .(x,"Tone:11,22,33,44,55"); } )
.cfv_level_tones_P <- cmpfun( function(x){ NULL; } )

feature.defs <- c(feature.defs, "contour_tones"=".cfv_contour_tones");
.cfv_contour_tones_F <- cmpfun( function(x){ .(x,"GC:ss") & !.cfv_level_tones_F(x); } )
.cfv_contour_tones_P <- cmpfun( function(x){ NULL; } )

# frication classes:
feature.defs <- c(feature.defs, "bilabial.fricatives"=".cfv_bilabial.fricatives");
.cfv_bilabial.fricatives_F <- cmpfun( function(x){ .(x,"CP:b") & .(x,"CM:f"); } )
.cfv_bilabial.fricatives_P <- cmpfun( function(x){ .(x,"+cons") & .(x,"-sonorant") & .(x,"-approx") & .(x,"+cont") & .(x,"+delayRel") & .(x,"+labial") & .(x,"-labiodent"); } )

feature.defs <- c(feature.defs, "labiodental.fricatives"=".cfv_labiodental.fricatives");
.cfv_labiodental.fricatives_F <- cmpfun( function(x){ .(x,"CP:ld") & .(x,"CM:f"); } )
.cfv_labiodental.fricatives_P <- cmpfun( function(x){ .(x,"+cons") & .(x,"-sonorant") & .(x,"-approx") & .(x,"+cont") & .(x,"+delayRel") & .(x,"+labial") & .(x,"+labiodent"); } )

feature.defs <- c(feature.defs, "alveolar.fricatives"=".cfv_alveolar.fricatives");
.cfv_alveolar.fricatives_F <- cmpfun( function(x){ .(x,"CP:a") & .(x,"CM:f"); } )
.cfv_alveolar.fricatives_P <- cmpfun( function(x){ .(x,"+cons") & .(x,"-sonorant") & .(x,"-approx") & .(x,"+cont") & .(x,"+delayRel") & .(x,"-labial") & .(x,"0labiodent") & .(x,"+coronal") & .(x,"+anterior") & .(x,"-distrib"); } )

feature.defs <- c(feature.defs, "nonsibilant.dental.fricatives"=".cfv_nonsibilant.dental.fricatives");
.cfv_nonsibilant.dental.fricatives_F <- cmpfun( function(x){ .(x,"CP:i") & .(x,"CM:f"); } )
.cfv_nonsibilant.dental.fricatives_P <- cmpfun( function(x){ .(x,"+cons") & .(x,"-sonorant") & .(x,"-approx") & .(x,"+cont") & .(x,"+delayRel") & .(x,"0labiodent") & .(x,"+coronal") & .(x,"+anterior") & .(x,"+distrib") & .(x,"-strident"); } )

feature.defs <- c(feature.defs, "sibilant.dental.fricatives"=".cfv_sibilant.dental.fricatives");
.cfv_sibilant.dental.fricatives_F <- cmpfun( function(x){ .(x,"CP:d") & .(x,"CM:f"); } )
.cfv_sibilant.dental.fricatives_P <- cmpfun( function(x){ .(x,"+cons") & .(x,"-sonorant") & .(x,"-approx") & .(x,"+cont") & .(x,"+delayRel") & .(x,"0labiodent") & .(x,"+coronal") & .(x,"+anterior") & .(x,"+distrib") & .(x,"+strident"); } )

feature.defs <- c(feature.defs, "bilabiallabiodental.affricates"=".cfv_bilabiallabiodental.affricates");
.cfv_bilabiallabiodental.affricates_F <- cmpfun( function(x){ .(x,"CP:bld") & .(x,"CM:af"); } )
.cfv_bilabiallabiodental.affricates_P <- cmpfun( function(x){ .(x,"+cons") & .(x,"-sonorant") & .(x,"-approx") & .(x,"-cont") & .(x,"+delayRel") & .(x,"+labial") & .(x,"+labiodent"); } )

feature.defs <- c(feature.defs, "bilabial.affricates"=".cfv_bilabial.affricates");
.cfv_bilabial.affricates_F <- cmpfun( function(x){ .(x,"CP:b") & .(x,"CM:af"); } )
.cfv_bilabial.affricates_P <- cmpfun( function(x)
{ 
  y <- .(x,"+cons") & .(x,"-sonorant") & .(x,"-approx") & .(x,"-cont") & .(x,"+delayRel") & .(x,"+labial") & .(x,"-labiodent");  
  z <- vapply(seq_along(y), function(i) if(!y[i]) {FALSE} else {all(str_trim(strsplit(x[i,"labial"],",",fixed=TRUE)[[1]])=="+") & all(str_trim(strsplit(x[i,"labiodent"],",",fixed=TRUE)[[1]])=="-")}, logical(1)); names(z) <- names(y); # for all complex (multi-valued) segments, check that all the components are [+labial] and [-labiodent]
  z;
} )

# retroflex classes:
feature.defs <- c(feature.defs, "retroflex.stops"=".cfv_retroflex.stops");
.cfv_retroflex.stops_F <- cmpfun( function(x){ .(x,"CP:r") & .(x,"CM:s"); } )
.cfv_retroflex.stops_P <- cmpfun( function(x){ .(x,"+cons") & .(x,"-sonorant") & .(x,"-approx") & .(x,"-cont") & .(x,"-delayRel") & .(x,"0labiodent") & .(x,"+coronal") & .(x,"-anterior") & .(x,"-distrib"); } )

feature.defs <- c(feature.defs, "retroflex.fricatives"=".cfv_retroflex.fricatives");
.cfv_retroflex.fricatives_F <- cmpfun( function(x){ .(x,"CP:r") & .(x,"CM:f"); } )
.cfv_retroflex.fricatives_P <- cmpfun( function(x){ .(x,"+cons") & .(x,"-sonorant") & .(x,"-approx") & .(x,"+cont") & .(x,"+delayRel") & .(x,"0labiodent") & .(x,"+coronal") & .(x,"-anterior") & .(x,"-distrib"); } )

feature.defs <- c(feature.defs, "retroflex.affricates"=".cfv_retroflex.affricates");
.cfv_retroflex.affricates_F <- cmpfun( function(x){ .(x,"CP:r") & .(x,"CM:af"); } )
.cfv_retroflex.affricates_P <- cmpfun( function(x){ .(x,"+cons") & .(x,"-sonorant") & .(x,"-approx") & .(x,"-cont") & .(x,"+delayRel") & .(x,"0labiodent") & .(x,"+coronal") & .(x,"-anterior") & .(x,"-distrib"); } )

feature.defs <- c(feature.defs, "retroflex.nasals"=".cfv_retroflex.nasals");
.cfv_retroflex.nasals_F <- cmpfun( function(x){ .(x,"CP:r") & .(x,"CM:n"); } )
.cfv_retroflex.nasals_P <- cmpfun( function(x){ .(x,"+cons") & .(x,"+sonorant") & .(x,"-approx") & .(x,"-tap") & .(x,"-trill") & .(x,"+nasal") & .(x,"0labiodent") & .(x,"+coronal") & .(x,"-anterior") & .(x,"-distrib"); } )

feature.defs <- c(feature.defs, "retroflex.approximants"=".cfv_retroflex.approximants");
.cfv_retroflex.approximants_F <- cmpfun( function(x){ .(x,"CP:r") & .(x,"CM:a,tr,t"); } )
.cfv_retroflex.approximants_P <- cmpfun( function(x){ .(x,"-syll") & .(x,"+sonorant") & .(x,"+approx") & .(x,"0labiodent") & .(x,"+coronal") & .(x,"-anterior") & .(x,"-distrib"); } )


################################
#
# Feature counting
#
################################

count.features <- function(inventory, inventory.name="", use.system=c("phoible","fonetikode","ruhlen"))
{
  # For a given inventory (inv) and phonemic description (pho), extract those segments that actually occur in the inventory:
  extract.phonemic.description <- function( inv, pho )
  {
    # Select those rows in pho for which the Phoneme is defined in inv (i.e. is 1):
    s <- (as.character(pho$Phoneme) %in% names(inv)[inv==1]);
    pho <- pho[s,];
    return (pho[order(pho$Phoneme),]);
  }
  
  # Apply the counting functions (defined by a suffix, "M" or "P") to the given segments subset:
  # Return a list with the counts (for the features that could be counted) and the text to be exported to the logfile
  do.counting <- function( suffix=c("M","P"), segments.subset, uulid, log.file.name=NULL )
  {
    counts <- rep(-Inf,length(feature.defs)); names(counts) <- names(feature.defs);
    logtext <- NULL;
    for( i in 1:length(feature.defs) )
    {
      s <- names(feature.defs)[i];
      f <- get(paste0(feature.defs[i],"_",suffix));
      res <- f(segments.subset); # call the corresponding function
      count <- ifelse( !is.null(res), sum(res), NA );
      logmessage <- paste0( uulid, "\t", 
                           s, "\t", 
                           count, "\t", 
                           ifelse( is.null(res), "NULL", paste0("{ ", 
                                                               ifelse( is.logical(res), paste0(names(res)[res],collapse=" "),  paste0(names(res),collapse=" ")),
                                                               " }") ), 
                           "\n");
      if( !is.null(log.file.name) ) cat(logmessage, file=log.file.name, append=TRUE) else logtext <- c(logtext, logmessage);
      counts[i] <- count;
    }
    return (list("counts"=counts[!is.infinite(counts)], "logtext"=paste(logtext,sep="",collapse=""))); # return only the features that could be computed
  }
  
  # Create the log files and subset the appropriate data:
  dir.create("../output/logs", showWarnings=FALSE);
  if( use.system == "phoible" )
  {
    log.file <- paste0("../output/logs/", inventory.name, "--phoible-features.csv");
    phonemes.to.use <- phonemes.phoible;
    suffix <- "P";
  } else if( use.system == "fonetikode" )
  {
    log.file <- paste0("../output/logs/", inventory.name, "--fonetikode-features.csv");
    phonemes.to.use <- phonemes.fonetikode;
    suffix <- "M";
  } else if( use.system == "ruhlen" )
  { 
    log.file <- paste0("../output/logs/", inventory.name, "--fonetikode-features.csv");
    phonemes.rhulen.extended <- rbind(phonemes.rhulen, phonemes.fonetikode[,-1]); # Ruhlen's must be concatenated to Fonetikode:
    phonemes.to.use <- phonemes.rhulen.extended;
    suffix <- "M";
  } else
  {
    stop(paste0("Unknown system '", use.system, "'!\n"));
  }
  
  feature.counts <- lapply(1:nrow(inventory), function(i)
  #feature.counts <- lapply(1:10, function(i) # i=606 (English), 1546 (Dutch)
    {
      # Progress:
      if( i %% 100 == 1 )
      {
        cat(paste0("For ", inventory.name, " + ", use.system, ": processing language ", inventory$UULID[i], ", ", i, " out of ", nrow(inventory), " (", sprintf("%.1f", 100*i/nrow(inventory)), "%)\n"));
      }
      
      # Extract the current inventory:
      inv <- inventory[i,(which(names(inventory)=="UULID")+1):ncol(inventory)];
    
      # The actually present phonemes in the current language's inventory:
      phonemes.subset <- extract.phonemic.description(inv, phonemes.to.use);      
      if( nrow(phonemes.subset) > 1 )
      {
        tmp <- do.counting(suffix, phonemes.subset, inventory$UULID[i], NULL);
        phonemes.counts <- tmp$counts;
        logtext <- tmp$logtext;
      } else
      {
        phonemes.counts <- NULL;
        logtext <- NA;
      }
      
      # Return value:
      return (c("LOGTEXT"=logtext, "UULID"=inventory$UULID[i], phonemes.counts));
    } );
  
  # Write the log file header:
  cat("UULID\tFeature\tCount\tClass.membership\n", file=log.file, append=FALSE);
  
  # Convert them to a matrix (and write the log file body):
  all.names <- NULL;
  for( i in seq_along(feature.counts) )
  {
    if( !is.na(feature.counts[[i]][1]) ) cat(feature.counts[[i]][1], file=log.file, append=TRUE);
    all.names <- union(all.names, names(feature.counts[[i]])[-1]);
  }
  all.names <- all.names[ all.names != "UULID" ];
  results <- matrix(NA, nrow=length(feature.counts), ncol=length(all.names));
  rownames(results) <- vapply(feature.counts, function(s) s["UULID"], character(1));
  colnames(results) <- all.names;
  for( i in 1:nrow(results) )
  {
    tmp <- feature.counts[[i]];
    for( j in 1:ncol(results) ) results[i,j] <- as.numeric(tmp[all.names[j]]);
  }
  results <- cbind("UULID"=rownames(results), data.frame(results));
  
  # Return the counts:
  return (results);
}
count.features <- cmpfun(count.features);

# Count the inventories (takes a long time!):
library(parallel);
cases <- read.table(header=TRUE, stringsAsFactors=FALSE,
                    text="Inventory            Name      System
                          phoible.inventories  phoible   phoible
                          phoible.inventories  phoible   fonetikode
                          rhulen.inventories   ruhlen    ruhlen");
tmp <- mclapply(1:nrow(cases), function(i)
  {
    segments.count <- count.features(inventory=get(cases$Inventory[i]), inventory.name=cases$Name[i], use.system=cases$System[i]);
    write.table(segments.count, paste0("../output/counts-",cases$System[i],".csv"), row.names=FALSE, sep="\t", quote=FALSE );
  }, mc.cores=3); # mc.cores=1);

# Combine the data:
counts.phoible    <- read.table("../output/counts-phoible.csv", header=TRUE, sep="\t", quote="", stringsAsFactors=FALSE); 
counts.fonetikode <- read.table("../output/counts-fonetikode.csv", header=TRUE, sep="\t", quote="", stringsAsFactors=FALSE); 
counts.ruhlen     <- read.table("../output/counts-ruhlen.csv", header=TRUE, sep="\t", quote="", stringsAsFactors=FALSE); 
library(dplyr);
names(counts.phoible)[2:ncol(counts.phoible)]       <- vapply(names(counts.phoible)[2:ncol(counts.phoible)],       function(s) paste0(s,"_P"), character(1));
names(counts.fonetikode)[2:ncol(counts.fonetikode)] <- vapply(names(counts.fonetikode)[2:ncol(counts.fonetikode)], function(s) paste0(s,"_F"), character(1));
names(counts.ruhlen)[2:ncol(counts.ruhlen)]         <- vapply(names(counts.ruhlen)[2:ncol(counts.ruhlen)],         function(s) paste0(s,"_R"), character(1));
counts <- full_join(counts.phoible, counts.fonetikode, by=c("UULID"="UULID"));
counts <- full_join(counts, counts.ruhlen, by=c("UULID"="UULID"));
counts <- cbind("ISO"=NA, "WALS"=NA, "AUTOTYP"=NA, "GLOTTOLOG"=NA, counts);
for( i in 1:nrow(counts) )
{
  s <- as.character(counts$UULID[i]);
  counts$ISO[i]       <- gsub("-",",",strsplit(strsplit(s,"[i-",fixed=TRUE)[[1]][2],"]",fixed=TRUE)[[1]][1],fixed=TRUE);
  counts$WALS[i]      <- gsub("-",",",strsplit(strsplit(s,"[w-",fixed=TRUE)[[1]][2],"]",fixed=TRUE)[[1]][1],fixed=TRUE);
  counts$AUTOTYP[i]   <- gsub("-",",",strsplit(strsplit(s,"[a-",fixed=TRUE)[[1]][2],"]",fixed=TRUE)[[1]][1],fixed=TRUE);
  counts$GLOTTOLOG[i] <- gsub("-",",",strsplit(strsplit(s,"[g-",fixed=TRUE)[[1]][2],"]",fixed=TRUE)[[1]][1],fixed=TRUE);
}
write.table(counts, "../output/counts-merged.csv", row.names=FALSE, sep="\t", quote=FALSE );



